[WIP] Changes to market state for Forest `StateMarketStorageDeal` RPC method
ChainSafe/fil-actor-states pull request #229
Opened 2023-12-15 11:38 UTC by jdjaustin

**Summary of changes**
Changes introduced in this pull request:
- Implement `states`, `proposals`, `for_each`, ... methods to properly implement Forest `StateMarketStorageDeal` RPC method ([related PR](https://github.com/ChainSafe/forest/pull/3815)).
- Update `derive` macros for `DealProposal` and `DealState`.

**Reference issue to close (if applicable)**

N/A

**Other information and links**

2024-01-10 12:32 UTC, jdjaustin commented
| RPC Method                          | Forest | Lotus |
|-------------------------------------|--------|-------|
| Filecoin.StateMarketStorageDeal (2) | Valid  | Valid |

2024-01-10 15:24 UTC, hanabi1224 commented on fil_actor_interface/src/builtin/market/mod.rs
> +            State::V8(_st) => unimplemented!(),
How about `anyhow::bail!("unimplemented")` rather than panicking with `unimplemented!()`?

2024-01-10 15:24 UTC, hanabi1224 approved these changes

2024-01-11 12:52 UTC, LesnyRumcajs requested changes

2024-01-11 14:12 UTC, jdjaustin commented on fil_actor_interface/src/builtin/market/mod.rs
> +                                    String::from_utf8(b.clone()).unwrap()
Fixed.

2024-01-16 09:47 UTC, jdjaustin commented on fil_actor_interface/src/builtin/market/mod.rs
> +            DealProposals::V9(deal_array) => {
I think we can avoid verbatim repetition like in V10/V11, although there may still be some repetition in the macros, but I'll see what I can do to reduce it.

2024-01-16 18:35 UTC, jdjaustin commented on fil_actor_interface/src/builtin/market/mod.rs
> +            DealProposals::V9(deal_array) => {
I didn't have success with generalizing this over a macro. Even V10/V11 have a subtle difference in the `deal_proposal.label` parsing that seems to require custom treatment, so everything I tried simply moved the repetition over to the macros and didn't really seem to be a better solution. However, the solution I did come up with (adding a `From` impl for the different `DealProposal` variants) can at least be reused elsewhere in the codebase if needed and follows our code style in the miner actor as well as over in forest_shim. If I'm missing something or you think of a better solution, please let me know!

2024-01-22 11:57 UTC, LesnyRumcajs commented on fil_actor_interface/src/builtin/market/mod.rs
> +                    String::from_utf8(b.clone()).expect("failed to deserialize utf8 string")
Are we 100% sure this won't fail? If not, it might make more sense to implement `TryFrom`. Same of the other versions.

2024-01-23 14:12 UTC, LesnyRumcajs commented on fil_actor_interface/src/builtin/market/mod.rs
> +                            .expect("failed to convert V9 deal proposal to builtin version"),
Well, we moved the error handling one lever higher but it's not high enough. Ideally, the library code should **never** panic, unless there was a huge violation of expectations to our own logic. Can we let the calling code deal with this?

All in all, the goal is to evade crashing the application unless it doesn't make sense for it to continue.

2024-01-24 09:33 UTC, LesnyRumcajs approved these changes

2024-01-24 09:40 UTC, merged