Added manifest cids to known cids
ChainSafe/fil-actor-states pull request #81
Opened 2023-04-05 11:32 UTC by sudo-shashank

**Summary of changes**
Changes introduced in this pull request:
- Added a new `manifest_cids.yaml` file 
- `KnownCids` now contains two fields `manifest` and `actor`. 
- Added to test 

**Reference issue to close (if applicable)**

Closes #77 

**Other information and links**

2023-04-05 14:52 UTC, lemmih commented
@LesnyRumcajs Probably need your eyes on this.

2023-04-06 13:33 UTC, sudo-shashank commented
added test:
https://github.com/ChainSafe/fil-actor-states/blob/fd7cae9fc874bf369d64f1e5300c68fb758b8ce9/fil_actor_interface/src/builtin/known_cids.rs#L88-L95

2023-04-11 10:00 UTC, LesnyRumcajs requested changes
This should be a compilation failure (or at the very least a runtime error, but if we are generating code, then I believe it belongs to the static domain). 
```
println!("{}", KNOWN_CIDS.actor.placeholder.v8.mainnet);
```
instead, it prints (I guess) a default Cid.
```
baeaaaaa
```

We should prevent the user of this library from using things that don't make sense. We know that there is no placeholder actor for NV16, non-protocol engineer may not.

2023-04-11 10:00 UTC, LesnyRumcajs commented on fil_actor_interface/src/builtin/manifest_cids.yaml
> +mainnet:
It would be useful to point to a specific bundle/git tag, same as Lotus does.

2023-04-11 10:00 UTC, LesnyRumcajs commented on fil_actor_interface/src/builtin/known_cids.rs
> +pub struct CidPerNetworkVersion {
Is `v8` the network version?

2023-04-12 11:58 UTC, sudo-shashank commented on fil_actor_interface/src/builtin/known_cids.rs
> +pub struct CidPerNetworkVersion {
fix: changed to `CidPerVersion`

2023-04-12 13:56 UTC, LesnyRumcajs commented
@sudo-shashank Options are awkward in this case. During code generation, we **know** that there is no `placeholder` actor for `v9`, but there's one for `v10`. Can we not generate it, then? `Option` is okay in cases we don't know before running the program, for example, because it lives on the chain (not applicable here). We have all the blocks to make a static solution in this case. What do you think?

2023-04-13 10:04 UTC, sudo-shashank commented
> @sudo-shashank Options are awkward in this case. During code generation, we **know** that there is no `placeholder` actor for `v9`, but there's one for `v10`. Can we not generate it, then? `Option` is okay in cases we don't know before running the program, for example, because it lives on the chain (not applicable here). We have all the blocks to make a static solution in this case. What do you think?

I think it make sense to have a static solution in this case, on it

2023-05-02 08:34 UTC, lemmih requested changes
Either statically encode which CIDs are available for which actors or use HashMaps.

2023-05-02 11:48 UTC, lemmih approved these changes

2023-05-04 11:26 UTC, LesnyRumcajs approved these changes

2023-05-04 11:28 UTC, LesnyRumcajs commented
Thanks @sudo-shashank. Are the yaml files automatically generated?

2023-05-04 14:00 UTC, sudo-shashank commented
> Thanks @sudo-shashank. Are the yaml files automatically generated?

Not yet, I'll create a new ticket for .yaml file generation

2023-05-04 14:00 UTC, merged